#!/bin/sh
set -e

### etc diff send mail ####

cd /etc/

git_diff=`git diff | head -n1 | cut -d " " -f 1`

if [ -n "$git_diff" ] ; then
     git diff | mail -s "$(hostname) git diff" MAILADDR
fi


### etckeeper default setting ###

if [ -x /usr/bin/etckeeper ] && [ -e /etc/etckeeper/etckeeper.conf ]; then
        . /etc/etckeeper/etckeeper.conf
        if [ "$AVOID_DAILY_AUTOCOMMITS" != "1" ]; then
                # avoid autocommit if an install run is in progress
                lockfile=/var/cache/etckeeper/packagelist.pre-install
                if [ -e "$pe" ] && [ -n "$(find "$lockfile" -mtime +1)" ]; then
                        rm -f "$lockfile" # stale
                fi
                if [ ! -e "$lockfile" ]; then
                        AVOID_SPECIAL_FILE_WARNING=1
                        export AVOID_SPECIAL_FILE_WARNING
                        if etckeeper unclean; then
                                etckeeper commit "daily autocommit" >/dev/null
                        fi
                fi
        fi
fi
